### ISSUE TITLE
gedit opens with "unhandled-exception.log"

### ISSUE THREAD

**Issue by rrschmidt** [curiosity-ai/curiosity-desktop-linux#3]
After setting up the Beta for Linux on my Ubuntu 20 LTS and connecting to various apps (which likely triggered some heavy indexing), I saw these symptoms: 

- the system became extremly slow and started massive swapping
- according to htop curiosity used >25GB of RAM (on a 32 GB machine)
- at some point the situation normalized (strangely I didn't find any obvious traces of the oom-reaper in the syslogs)
- and this message popped up in a gedit window: 

```
Sorry, there was an error :(

Please send this file to hello@curiosity.ai to help us fix the problem!

 Error details:
Unhandled Exception, will terminate now!
System.InvalidOperationException: byte[] size reached maximum size of array(0x7FFFFFC7), can not write to single byte[]. Details: https://msdn.microsoft.com/en-us/library/system.array
   at void MessagePackCompat.MessagePackBinary.EnsureCapacity(ref byte[] bytes, int offset, int appendLength)
   at int MessagePackCompat.MessagePackBinary.WriteSingle(ref byte[] bytes, int offset, float value)
   at int Mosaik.GraphDB._DocumentSerializer.SerializeDoc(ImmutableDocument doc, int offset, ref byte[] bytes)
   at byte[] Mosaik.GraphDB._DocumentSerializer.Serialize(_Document docNode)
   at byte[] Mosaik.GraphDB.GraphStorage.NodeToLogBytes(LockedNode lockedNode)
   at void Mosaik.GraphDB.GraphStorage.Log(LockedNode nodeA, LockedNode nodeB)
   at void Mosaik.GraphDB.GraphStorage.ReleaseUpdate(LockedNode nodeA, LockedNode nodeB, bool log)
   at ValueTask Mosaik.GraphDB.Graph.CommitAsync(LockedNode nodeA, LockedNode nodeB, bool log)
   at async IActionResult Mosaik.Server.Controllers.FilesController.IngestTextContentWithToken(UID128 uid, string token, DocumentText document)+(?) => { }
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at void System.Threading.QueueUserWorkItemCallback.s_executionContextShim(QueueUserWorkItemCallback quwi)
   at void System.Threading.QueueUserWorkItemCallback.Execute()
   at bool System.Threading.ThreadPoolWorkQueue.Dispatch()
   at void System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

**Comment by theolivenbaum** [comment]
Hi @rrschmidt,

Thanks for the report! Just to help debugging the issue, which apps did you connect? Did you connect local files as well?

From a quick glance it seems like a very large file was being processed by the app, with over 2GB of text. 

This would explain the temporary memory usage as well - as we need to hold the data in memory till it's written to disk. I'll

Kind regards,

Rafael

**Comment by rrschmidt** [comment]
Connect apps? Many:

1. Files: yes - my project folder and there might be files with 2GB+ size ... guess your indexing can ignore such big files as they likely don't hold any usable information
2. Clipboard
3. Slack
4. Gmail  
5. Jira
6. Github
7. Google Calendar
8. Stackoverflow
9. Google drive (might also hold a few big files, although 2GB sounds a bit too big)
10. XKCD

**Comment by rrschmidt** [comment]
This issue also seems to be persistent and keeps stopping the indexing (tried running it over night two times now)

**Comment by rrschmidt** [comment]
![image](https://user-images.githubusercontent.com/3114934/151309560-3532a6d9-a6ee-4d13-a437-449cd9908cbd.png)

Does this help? The red selected rectangle is a 1.1 GB file. 
All in all that's 44 GB of project files, mostly source code, but also with some images, zipped data dumps etc in between that can be 100s MBs or sometimes even slightly above 1 GB.

**Comment by theolivenbaum** [comment]
@rrschmidt can you try the latest release: https://github.com/curiosity-ai/curiosity-app-linux/releases/tag/v1.0.24993

**Comment by rrschmidt** [comment]
Thank you, the gedit report disappeared, but it seems that there are still problems: 

After running (and likely indexing in the background) for ~0.5 days the system gets extremely slow though memory and cpu look loaded but ok. After a while curiosity is gone and the system back to normal. 

I went through this a few times.

I check the system logs and it seems that this was no memory problem. At least I see no activity by the oom-reaper.

Also for the last two times this happened (Feb 1 and Feb 2) there absolutely nothing to be found in the logs. 

For Jan 31 I found this here: 

```
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.I.LuceneTextIndex] [WRITE-RDB] LuceneTextIndexData-Any-v6 (302 B) from to '..//Graph/v000006/--/LuceneTextIndexData/model-MosaikGraph-_Calendar-Name-v000006.bin'
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.I.LuceneTextIndex] [WRITE-RDB] LuceneTextIndexData-Any-v6 (305 B) from to '..//Graph/v000006/--/LuceneTextIndexData/model-MosaikGraph-_Ticket-Subject-v000006.bin'
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.I.LuceneTextIndex] [WRITE-RDB] LuceneTextIndexData-Any-v6 (305 B) from to '..//Graph/v000006/--/LuceneTextIndexData/model-MosaikGraph-_AccessGroup-Name-v000006.bin'
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.I.LuceneTextIndex] [WRITE-RDB] LuceneTextIndexData-Any-v6 (314 B) from to '..//Graph/v000006/--/LuceneTextIndexData/model-MosaikGraph-_AccessGroup-Description-v000006.bin'
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.I.LuceneTextIndex] [WRITE-RDB] LuceneTextIndexData-Any-v6 (304 B) from to '..//Graph/v000006/--/LuceneTextIndexData/model-MosaikGraph-_Collection-Name-v000006.bin'
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.I.LuceneTextIndex] [WRITE-RDB] LuceneTextIndexData-Any-v6 (302 B) from to '..//Graph/v000006/--/LuceneTextIndexData/model-MosaikGraph-_User-UserName-v000006.bin'
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.Q.I.IQueue] Queued task Mark file as finished indexed gj9u9W6D6Yf3f4ttEPS4rh finished in 71.0 ms...
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.I.SimpleTextIndex] [WRITE-RDB] SimpleTextIndexData-Any-v6 (20.1 MB) from to '..//Graph/v000006/--/SimpleTextIndexData/model-MosaikGraph-_FileEntry-Source-v000006.bin'
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.I.SimpleTextIndex] [WRITE-RDB] SimpleTextIndexData-Any-v6 (20.3 MB) from to '..//Graph/v000006/--/SimpleTextIndexData/model-MosaikGraph-_FileEntry-ContentType-v000006.bin'
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.I.NumericIndex] [WRITE-RDB] NumericIndexData`1-Any-v6 (20.4 MB) from to '..//Graph/v000006/--/NumericIndexData`1/model-MosaikGraph-_FileEntry-Size-v000006.bin'
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.Q.I.IQueue] Queued task Ingest text content from file YhD4NiWXTGRW7pqCiqZjks finished in 343.0 ms...
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.Q.I.IQueue] Queued task Mark file as finished indexed eMvAWbKvxDh3GzspxksKpH finished in 78.0 ms...
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.I.SimpleTextIndex] [WRITE-RDB] SimpleTextIndexData-Any-v6 (20.2 MB) from to '..//Graph/v000006/--/SimpleTextIndexData/model-MosaikGraph-_FileEntry-Extension-v000006.bin'
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.Graph] [E] Uploading indexes to storage in 6.6000 seconds
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.GraphStorage] [B] [MEM: 3111.69 MB] Storing nodes from cache
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stderr: [fail] [14:24:37] [M.S.MosaikStartup] Error running task on queue
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: System.Exception: Cannot call ReleaseUpdate when in read-only mode!
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]:    at Mosaik.GraphDB.Graph.ThrowCantChangeWhenGraphIsLocked(String method)
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]:    at Mosaik.GraphDB.GraphStorage.ReleaseUpdate(LockedNode node, Boolean log)
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]:    at Mosaik.GraphDB.Graph.CommitAsync(LockedNode node, Boolean log)
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]:    at Mosaik.Server.Controllers.FilesController.<>c__DisplayClass50_0.<<MarkIndexingAsFinished>b__0>d.MoveNext()
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: --- End of stack trace from previous location ---
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]:    at Mosaik.Tasks.ActionOrAsyncFunc.Invoke(Graph graph)
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]:    at Mosaik.Queuing.Queue.InvokeTask(ActionOrAsyncFunc task, Graph graph)
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.GraphStorage] [E] [MEM: 3111.69 MB] Storing nodes from cache in 0.0577 seconds at 8,856 oper/s, total of 511 operations
Jan 31 14:24:37 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:37] [M.G.GraphStorage] [MEM: 3114.11 MB]  Stored 511 nodes from cache
Jan 31 14:24:38 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:38] [M.G.RocksDbStorage] [B] Cleaning up WAL
Jan 31 14:24:39 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:39] [M.G.RocksDbStorage] [E] Cleaning up WAL in 1.1800 seconds
Jan 31 14:24:39 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:39] [M.G.Graph] [E] Uploading data to storage in 1.5500 seconds
Jan 31 14:24:39 rs-az-pc4 curiosity.desktop[1011196]: stdout: [warn] [14:24:39] [M.S.MosaikStartup] Finished storing graph, will shutdown server now.
Jan 31 14:24:39 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [14:24:39] [M.S.MosaikStartup] [E] Stoping and storing graph in 11.0300 seconds
Jan 31 14:24:40 rs-az-pc4 curiosity.desktop[1011196]: stdout: [warn] [14:24:40] [M.Q.H.QueuingHost] Queuing service is attempting to close but the queue is still running. App closing (in background) will be prevented until dequeued tasks are completed.
Jan 31 14:24:47 rs-az-pc4 gnome-shell[3123]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x6e000f8
Jan 31 14:25:01 rs-az-pc4 CRON[1025191]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)

....
Jan 31 15:00:17 rs-az-pc4 slack.desktop[6591]: [01/31/22, 15:00:17:252] info: [CHECK-FOR-OLD-IMS] (T9ND0QZAQ) Within limit [external DMs]: 0
Jan 31 15:00:17 rs-az-pc4 slack.desktop[6591]: [01/31/22, 15:00:17:252] info: [CHECK-FOR-OLD-IMS] (T9ND0QZAQ) Within limit [internal DMs]: 10
Jan 31 15:00:31 rs-az-pc4 curiosity.desktop[1011196]: stdout: [info] [15:00:31] [M.D.DesktopClient] Opening settings
Jan 31 15:00:31 rs-az-pc4 curiosity.desktop[1011196]: stderr: [fail] [15:00:31] [M.D.DesktopClient] Error running background task OpenSettingsAsync
Jan 31 15:00:31 rs-az-pc4 curiosity.desktop[1011196]: Mosaik.GraphDB.GraphIsClosedException: Exception of type 'Mosaik.GraphDB.GraphIsClosedException' was thrown.
Jan 31 15:00:31 rs-az-pc4 curiosity.desktop[1011196]:    at Mosaik.GraphDB.Graph.ThrowGraphClosed()
Jan 31 15:00:31 rs-az-pc4 curiosity.desktop[1011196]:    at Mosaik.GraphDB.Graph.TryGetWithoutEdges(UID128 uid, ReadOnlyNodeWithoutEdges& node)
Jan 31 15:00:31 rs-az-pc4 curiosity.desktop[1011196]:    at Mosaik.Desktop.App.<>c__DisplayClass5_1.<Main>b__12(String route)
Jan 31 15:00:31 rs-az-pc4 curiosity.desktop[1011196]:    at Mosaik.Desktop.DesktopClient.OpenSettingsAsync(Boolean center)
Jan 31 15:00:31 rs-az-pc4 curiosity.desktop[1011196]:    at Mosaik.Desktop.Dispatcher.<>c__DisplayClass2_0.<<RunTask>b__0>d.MoveNext()
Jan 31 15:00:55 rs-az-pc4 slack.desktop[6591]: [01/31/22, 15:00:55:835] info: [RTM] (T3XALNPJN) Processed 1 dnd_updated_user event(s) over 0.10ms
Jan 31 15:01:03 rs-az-pc4 slack.desktop[6591]: [01/31/22, 15:01:03:198] info: [RTM] (T3XALNPJN) Processed 1 file_deleted event(s) over 0.00ms
```

But I'm not fully sure whether this was right before installing the new release or afterwards

Anywhere else I could/should look?
